# Configuration du serveur
server.port=8282

# Configuration de l'application
spring.application.name=jenkins-demo

# Configuration des logs
logging.level.root=INFO
logging.level.com.example.jenkinsdemo=DEBUG
